### ISSUE TITLE
additional installation

### ISSUE THREAD

**Issue by makabe0510** [iory/pptx-tools#3]
In my environment (Ubuntu18.04.1), the following additional installation was required to execute the slide-add-voice command.

```
pip install azure
pip install azure-cognitiveservices-vision-computervision
pip install azure-cognitiveservices-speech
pip install --upgrade google-cloud-texttospeech
```

**Comment by iory** [comment]
https://github.com/iory/pptx-tools/pull/8
I have separated the dependencies for Azure. If you encounter any problems during installation, please report back.
